# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYTDemo
pod 'Alamofire'
pod 'SDWebImage', '~> 4.0'
pod 'lottie-ios'
pod 'ReachabilitySwift'
pod 'Cosmos', '~> 17.0'
pod 'SwiftIconFont'
pod 'ScrollViewKeyboardAvoider', '~> 1.0'
pod 'KeyboardFrameChangeListener', '~> 1.0'

  target 'NYTDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
